spring:

  profiles:
    active: dev

  application:
    name: learnspeing


  data:
    mongodb:
      host: localhost
      port: 27017
      database: journal_db
      auto-index-creation: true
      # Uncomment and set these if authentication is required
      # authentication-database: admin
      # username: <username>
      # password: <password>
      # uri: mongodb://<username>:<password>@<host>:<port>/<database>?authSource=admin

#
#logging:
#  level:
#    root: warm

  mail:
    host: smtp.gmail.com              # Replace with your SMTP host
    port: 587                         # Port for TLS; use 465 for SSL
    username: mohitpandey22505@gmail.com    # Your email address
    password: oxzl kneo itte yljy     # Your email password or app password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true                  # Enable authentication
          starttls:
            enable: true              # Enable STARTTLS



weather:
  api:
    key: bc0f5d800959a210ea236834d989c9eb