# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml  :

      
      - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://hp-junoon --delete   
      
      - name: Spring boot image build jdk17
  # You may pin to the exact commit or the version.
  # uses: teheidoma/spring-boot-image-build-action-jdk17@37dabb42624700d79ef0b9afc7230254b81b4d40
  uses: teheidoma/spring-boot-image-build-action-jdk17@0.0.3
  with:
    # registry username
    registry_username: # optional
    # registry password
    registry_password: # optional
    # registry hostname
    registry_hostname: # optional, default is docker.io
    # include commit SHA to image tag
    include_commit_sha: # optional, default is false
          
